"""add status in EmailToSend

Revision ID: 69775189e3fe
Revises: e61e537fc7c0
Create Date: 2019-04-29 10:34:06.791468

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '69775189e3fe'
down_revision = 'e61e537fc7c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_to_send', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_to_send', 'status')
    # ### end Alembic commands ###
