version: '3.6'

services:
  flask-for-you:
    container_name: flask_for_you
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - SQLALCHEMY_DATABASE_URI=postgres://flask_userforyou:passwordforyou@flask-db-for-you:5432/flask_foryou
      - API_VERSION=0.0.1
    depends_on:
      - flask-db-for-you
    ports:
      - 8000:8000
  flask-db-for-you:
    image: postgres
    container_name: flask_db_for_you
    environment:
      - POSTGRES_DB=flask_foryou
      - POSTGRES_USER=flask_userforyou
      - POSTGRES_PASSWORD=passwordforyou
    ports:
      - 5432:5432
    volumes:
      - "./docker/db-backups:/root/db-backups"
  rabbitmq-for-you:
    hostname: rabbitmq
    image: rabbitmq:3.7-management
    container_name: rabbitmq_for_you
    environment:
      RABBITMQ_DEFAULT_USER: rabbituser
      RABBITMQ_DEFAULT_PASS: rabbitpassword
    ports:
      - 5672:5672
      - 15672:15672