version: '3.6'

services:
  flask-for-you:
    container_name: flask_for_you
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - SQLALCHEMY_DATABASE_URI=postgres://userforflask:passwordforflask@flask-db-for-you:5432/dbforflask
      - API_VERSION=0.0.1
    depends_on:
      - db-for-you-flask
    ports:
      - 8000:8000
  db-for-you-flask:
    image: postgres
    container_name: db_for_you_flask
    environment:
      - POSTGRES_DB=dbforflask
      - POSTGRES_USER=userforflask
      - POSTGRES_PASSWORD=passwordforflask
    ports:
      - 5432:5432
    volumes:
      - "./docker/db-backups:/root/db-backups"
  rabbitmq-for-you:
    hostname: rabbitmq
    image: rabbitmq:3.7-management
    container_name: rabbitmq_for_you
    environment:
      RABBITMQ_DEFAULT_USER: rabbituser
      RABBITMQ_DEFAULT_PASS: rabbitpassword
    ports:
      - 5672:5672
      - 15672:15672