version: '3.6'

services:
  django-for-you:
    container_name: django_for_you
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - DATABASE_URL=postgres://userfordjango:passwordfordjango@db-for-you-django:5432/dbfordjango
      - API_VERSION=0.0.2
    depends_on:
      - db-for-you-django
    ports:
      - 8000:8000
  db-for-you-django:
    image: postgres
    container_name: db_for_you_django
    environment:
      - POSTGRES_DB=dbfordjango
      - POSTGRES_USER=userfordjango
      - POSTGRES_PASSWORD=passwordfordjango
    ports:
      - 5432:5432
    volumes:
      - "./docker/db-backups:/root/db-backups"